# Expects:
# `./sites/samplekit.dev/.env.development' – vars will be baked into the image

name: sk-dev

services:
  db:
    image: postgres:latest
    container_name: sk-dev-db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - sites/samplekit.dev/.env.development
    ports:
      - '5432:5432'

  kv:
    image: redis:latest
    container_name: sk-dev-kv
    restart: unless-stopped
    volumes:
      - kv:/data
    env_file:
      - sites/samplekit.dev/.env.development
    ports:
      - '6379:6379'
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"

volumes:
  db:
    driver: local
  kv:
    driver: local
