##################### 🚧 WARNING: ENV VARS ARE BAKED INTO THE IMAGE 🚧 #####################
# Do not make resulting images public.
#
# Read Dockerfile.samplekit.gh for information.
#
# Do not make resulting images public.
##################### 🚧 WARNING: ENV VARS ARE BAKED INTO THE IMAGE 🚧 #####################

# Expects:
# permissions / variables / secrets defined in permissions.md

name: Check, build image, and publish to registry. Trigger the CapRover server to pull and deploy.

on:
  push:
    branches: [main, staging]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - run: pnpm install && pnpm --recursive build:dependencies && grep -o '^[^#]\+=' sites/samplekit.dev/.env.example > sites/samplekit.dev/.env && pnpm clean

  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG_SHA: ${{ steps.create_image_tags.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG: ${{ steps.create_image_tags.outputs.IMAGE_TAG }}
    steps:
      - name: Create Image Tags
        id: create_image_tags
        run: |
          echo "IMAGE_TAG_SHA=${{ vars.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.ref_name}}_$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "IMAGE_TAG=${{ vars.DOCKER_REGISTRY }}/${{ github.repository }}:latest" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=${{ vars.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

  build-publish:
    runs-on: ubuntu-latest
    needs: [check, setup]
    steps:
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image – production
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v5
        with:
          build-args: |
            "ENV_FILE=${{ secrets.ENV_FILE_PRODUCTION }}"
            "MODE=production"
          push: true
          file: Dockerfile.samplekit.gh
          tags: ${{ needs.setup.outputs.IMAGE_TAG }},${{ needs.setup.outputs.IMAGE_TAG_SHA }}

      - name: Build and push docker image – staging
        if: github.ref_name == 'staging'
        uses: docker/build-push-action@v5
        with:
          build-args: |
            "ENV_FILE=${{ secrets.ENV_FILE_STAGING }}"
            "MODE=staging"
          push: true
          file: Dockerfile.samplekit.gh
          tags: ${{ needs.setup.outputs.IMAGE_TAG }},${{ needs.setup.outputs.IMAGE_TAG_SHA }}

  pull-deploy:
    runs-on: ubuntu-latest
    needs: [setup, build-publish]
    steps:
      - name: Deploy CapRover App – production
        if: github.ref_name == 'main'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          app: ${{ vars.CR_APP }}
          server: ${{ vars.CR_SERVER }}
          token: ${{ secrets.CR_APP_TOKEN }}
          image: ${{ needs.setup.outputs.IMAGE_TAG }}

      - name: Deploy CapRover App – staging
        if: github.ref_name == 'staging'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          app: ${{ vars.CR_APP_STAGING }}
          server: ${{ vars.CR_SERVER }}
          token: ${{ secrets.CR_APP_TOKEN_STAGING }}
          image: ${{ needs.setup.outputs.IMAGE_TAG }}
